/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process.scheduling.visualizer.UI;

import Classes.SchedProcess;
import Drawing.ProcessBlock;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author armanmasangkay
 */
public class DrawPane extends javax.swing.JPanel implements ActionListener{
    Timer timer;
    int x=0, velX=2;
    SchedProcess process;
    ProcessBlock block1;
    /**
     * Creates new form DrawPane
     */
    public DrawPane() {
        initComponents();
        timer=new Timer(5,this);
        process=new SchedProcess("P1",2,5);
        block1=new ProcessBlock(process);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
//        g.setColor(Color.red);
//        g.fillRect(x, 30, 50, 30);
//        if(!timer.isRunning()){
//             timer.start();
//        }
        block1.show(g, 0, 0);
        
         
       
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
     // x=x+velX;
      repaint();
    }
    
   public static void main(String args[]) {
       DrawPane dp=new DrawPane();
       JFrame jf=new JFrame();
       jf.setTitle("Drawing Window");      
       jf.setSize(700,200);
       jf.setVisible(true);
       jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       jf.add(dp);
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
